[project]
name = "py-asoiaf-api"
version = "0.1.0"
description = "A tool to get ASOIAF quotes from an API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "dataclasses>=0.8",
    "requests>=2.32.3",
]
